app/urls.py
""" App url definitions """

from django.conf.urls import patterns, url, include

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', 'lists.views.home_page', name='home'),
    url(r'^lists/', include('lists.urls')),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^admin/', include(admin.site.urls)),
)

lists/urls.py
""" List url definitions """

from django.conf.urls import patterns, url

urlpatterns = patterns(
    'lists',
    url(r'^(\d+)/$', 'views.view_list', name='view_list'),
    url(r'^new$', 'views.new_list', name='new_list'),
)

lists/models.py
""" list models """

from django.db import models
from django.core.urlresolvers import reverse


class List(models.Model):
    """ List model """

    def get_absolute_url(self):
        """ generate and return the URL for this model instance """

        return reverse('view_list', args=[self.id])


class Item(models.Model):
    """ List item model """

    text = models.TextField()
    list = models.ForeignKey(List)

    class Meta:
        """ List item model metaclass """

        ordering = ('id', )
        unique_together = ('text', 'list')

    def __str__(self):
        """ return string representation of the instance """

        return self.text

lists/forms.py
""" list app forms """

from django import forms
from django.core.exceptions import ValidationError

from lists.models import Item


EMPTY_LIST_ERROR = 'You can\'t have an empty list item'
DUPLICATE_ITEM_ERROR = 'You\'ve already got this in your list'


class ItemForm(forms.models.ModelForm):
    """ item form """

    class Meta:
        """ item fomr meta """

        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg'
            })}

    def __init__(self, *args, **kwargs):
        """ Init item form object """

        super().__init__(*args, **kwargs)

        self.fields['text'].error_messages['required'] = EMPTY_LIST_ERROR

    def save(self, for_list):
        """ set current list instance """

        self.instance.list = for_list

        return super().save()


class ExistingListItemForm(ItemForm):
    """ existing list item form """

    def __init__(self, for_list, *args, **kwargs):
        """Init existing list item from object """

        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        """ do form uniqueness validation """

        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        """ don't use ItemForm.save """

        return forms.models.ModelForm.save(self)

lists/views.py
""" list view controller. """

from django.shortcuts import render, redirect

from lists.models import List
from lists.forms import ItemForm, ExistingListItemForm


def home_page(request):
    """ Render home page HTML. """

    return render(request, 'home.html', {'form': ItemForm()})


def view_list(request, list_id):
    """ Render list view page HTML """

    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)

    if 'POST' == request.method:
        form = ExistingListItemForm(for_list=list_, data=request.POST)

        if form.is_valid():
            form.save()

            return redirect(list_)

    return render(request, 'list.html', {'list': list_, 'form': form})


def new_list(request):
    """ Handle new list creation via HTTP POST """

    form = ItemForm(data=request.POST)

    if form.is_valid():
        list_ = List.objects.create()
        form.save(for_list=list_)

        return redirect(list_)
    else:
        return render(request, 'home.html', {'form': form})

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>To-Do lists</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css"
            media="screen" />
        <link rel="stylesheet" href="/static/base.css" media="screen" />
    </head>
    <body>
        <div class="container">

            <div class="row">
                <div class="col-md-6 col-md-offset-3 jumbotron">
                    <div class="text-center">
                        <h1>{% block header_text %}{% endblock %}</h1>

                        <form method="post"
                            action="{% block form_action %}{% endblock %}">
                            {{ form.text }}
                            {% csrf_token %}

                            {% if form.errors %}
                            <div class="form-group has-error">
                                <span class="help-block">{{ form.text.errors }}</span>
                            </div>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    {% block table %}{% endblock %}
                </div>
            </div>

        </div>
    </body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Stat a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
<table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
    <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
    {% endfor %}
</table>
{% endblock %}